# Generated by Django 5.1.2 on 2024-10-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sender',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
