# Generated by Django 5.1.2 on 2024-10-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notification',
            new_name='Notifications',
        ),
    ]
